version: '3.8'

services:
  backend-research:
    build:
      context: ./backend-research
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend-research/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  backend-video-embedding:
    build:
      context: ./backend-video-embedding
      dockerfile: Dockerfile
    ports:
      - "8010:8000"
    env_file:
      - ./backend-video-embedding/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:8000/health\")'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
